import { type BasicKeyValue } from "@/types/generic";

export const plantSectionValues: BasicKeyValue[] = [
  {
    label: "Dry Section From Infeed Bin to Holding Bin in)",
    value: "Dry Section From Infeed Bin to Holding Bin in)",
  },
  {
    label: "Separation Section (From Holding Bin Out to P1 and P2 Stockpiles)",
    value: "Separation Section (From Holding Bin Out to P1 and P2 Stockpiles)",
  },
  {
    label: "Total Plant Downtime",
    value: "Total Plant Downtime",
  },
];

export const sampleDescriptionValues: BasicKeyValue[] = [
  { label: "Plant Feed - Frm CNV -2", value: "Plant Feed - Frm CNV -2" },
  { label: "Dry Feed Frm CMV - 8", value: "Dry Feed Frm CMV - 8" },
  { label: "Product 1 ( Mags)", value: "Product 1 ( Mags)" },
  { label: "Product 2 (Non- Mags)", value: "Product 2 (Non- Mags)" },
];

export const validateHourValues: BasicKeyValue[] = [
  { label: "06h00", value: "06h00" },
  { label: "08h00", value: "08h00" },
  { label: "10h00", value: "10h00" },
  { label: "12h00", value: "12h00" },
  { label: "14h00", value: "14h00" },
  { label: "16h00", value: "16h00" },
  { label: "18h00", value: "18h00" },
  { label: "20h00", value: "20h00" },
  { label: "22h00", value: "22h00" },
  { label: "00h00", value: "00h00" },
  { label: "02h00", value: "02h00" },
  { label: "04h00", value: "04h00" }
];

export const sampleTypeValues: BasicKeyValue[] = [
  { label: "Normal Sample", value: "Normal Sample" },
  { label: "Special Sample", value: "Special Sample" },
  { label: "NS - No Sample", value: "NS - No Sample" },
];
export const plantValues: BasicKeyValue[] = [
  { label: "MP2", value: "MP2" },
  { label: "SAOB", value: "SAOB" },
  { label: "LIO", value: "LIO" },
];


export const disciplineValues: BasicKeyValue[] = [
  {
    label: "Instrumentation",
    value: "Instrumentation",
  },
  {
    label: "Electrical",
    value: "Electrical",
  },
  {
    label: "Compressor House",
    value: "Compressor House",
  },
  {
    label: "Safety",
    value: "Safety",
  },
  {
    label: "Mechanical",
    value: "Mechanical",
  },
  {
    label: "Operations",
    value: "Operations",
  },
  {
    label: "SAOB",
    value: "SAOB",
  },
  {
    label: "Bosveld",
    value: "Bosveld",
  },
];

export const plantEquipmentDescription: BasicKeyValue[] = [
  {
    label: "Plant Feed",
    value: "Plant Feed",
    options: [
      "Feed Stockpile Empty",
      "Wait for FEL",
      "FEL Breakdown in front of Bin",
      "Foreign Object in bin",
    ],
  },
  {
    label: "CV19",
    value: "CV19",
    options: [
      "CV19 Breakdown - Belt tear",
      "CV19 Breakdown Mechanical issue",
      "CV19 Breakdown Electrical issue",
      "Clean spillages on Conveyor",
      "Belt Slipping",
    ],
  },
  {
    label: "CV20",
    value: "CV20",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "Vibrating Grizzly Screen",
    value: "Vibrating Grizzly Screen",
    options: [
      "Clean Vibrator feeder / Remove Objects",
      "Mechanical Breakdown on Feeeder",
      "Electrical Breakdown on feeder",
      "Screen Panels Loose",
      "Screen Panel Replacement",
    ],
  },
  {
    label: "CV01",
    value: "CV01",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "Scale CV01",
    value: "Scale CV01",
    options: ["Test / Check Scale", "Clean Scale", "Calibrate / Repair scale"],
  },
  {
    label: "Scale CV08",
    value: "Scale CV08",
    options: [
      "Test / Check Scale",
      "Clean Scale",
      "Calibrate / Repair scale",
      "Balance Idlers",
    ],
  },
  {
    label: "Scale CV09",
    value: "Scale CV09",
    options: [
      "Test / Check Scale",
      "Clean Scale",
      "Calibrate / Repair scale",
      "Balance Idlers",
    ],
  },
  {
    label: "Scale CV10",
    value: "Scale CV10",
    options: [
      "Test / Check Scale",
      "Clean Scale",
      "Calibrate / Repair scale",
      "Balance Idlers",
    ],
  },
  {
    label: "CV002",
    value: "CV002",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV003",
    value: "CV003",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV007",
    value: "CV007",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV008",
    value: "CV008",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV09A",
    value: "CV09A",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV09B",
    value: "CV09B",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV10A",
    value: "CV10A",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV10B",
    value: "CV10B",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV17",
    value: "CV17",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "CV14",
    value: "CV14",
    options: [
      "Trip",
      "Belt cut",
      "Rock stuck in chute",
      "Gearbox",
      "Electrical / Instrumentation Trip",
      "Inspection",
      "Belt Slip - Tension",
      "Belt Drift Alignment",
      "Clean spillages on Conveyor",
      "Replace idler",
    ],
  },
  {
    label: "Coal Feed",
    value: "Coal Feed",
    options: [
      "Scale breakdown",
      "Clean spillages",
      "Belt failure",
      "Gearbox drive failure",
      "Bad Coal",
    ],
  },
  {
    label: "Furnace",
    value: "Furnace",
    options: [
      "Stoker failure",
      "Coal Chain Broke",
      "Repair Coal cutter",
      "Remove Bad Coal from Bin",
      "Low Temp",
      "Clean Stoker Bed- Coal Build up",
      "Blower fan",
      "Mechanical failure",
      "Electrical failure",
    ],
  },
  {
    label: "Kiln (Drier)",
    value: "Kiln (Drier)",
    options: [
      "Flights loose",
      "Drum Adjustment Roller/ Thrust Wheel  Issues",
      "Drive mechanism Grease",
      "Intake seal Damage / Repair",
      "Lubrication system",
      "Other",
      "Outlet seal damage / repair",
    ],
  },
  {
    label: "Drier Feed Screw 2 and Chute",
    value: "Drier Feed Screw 2 and Chute",
    options: ["Choked", "Mech Failure", "Trip", "Electrical failure"],
  },
  {
    label: "Scrubber",
    value: "Scrubber",
    options: [
      "Primary Venturi",
      "Secondary Venturi",
      "Process Water Low",
      "Water Balance",
      "Pump failure Scrubber pumps",
      "Pump Failure SAOB",
      "Valve Failure",
      "Instrumentation Failure",
      "Choking of pumps",
      "Cyclone Rotary Feeder Blocked / failed",
      "Other",
    ],
  },
  {
    label: "Cooling System",
    value: "Cooling System",
    options: [
      "Pump Failure",
      "Water Supply Issue",
      "Mech Failure",
      "Instrumentation failure",
      "Elect Failure",
      "Other",
    ],
  },
  {
    label: "Cooling screw",
    value: "Cooling screw",
    options: [
      "Pump Failure",
      "Water Supply Issue",
      "Cooling screw Mech Failure / bearings",
      "Screw breakdown",
      "Cooling tower Elect Failure",
      "Other",
    ],
  },
  {
    label: "Vibrating Screen and Tube Feeder",
    value: "Vibrating Screen and Tube Feeder",
    options: [
      "Tube Feeder Trip",
      "Screen panels replacement",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Inspection",
      "Operations",
    ],
  },
  {
    label: "Main Fan",
    value: "Main Fan",
    options: [
      "Inspection",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
    ],
  },
  {
    label: "SAOB",
    value: "SAOB",
    options: [
      "Pump Failure",
      "Water Supply Issue",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Mag Tower",
    value: "Mag Tower",
    options: [
      "Total Tower trip Operation",
      "High Bin level scavenger",
      "P1 or P2 Conveyor Trip",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Bucket elevator",
      "Scavenger feed Screw",
      "Bucket Elevator Feed Screws",
    ],
  },
  {
    label: "Surge  Bin and Feeder",
    value: "Surge  Bin and Feeder",
    options: [
      "Mechanical Failure",
      "Electrical failure",
      "Clean spillages",
      "Drier Stop Bin Full",
      "Choking",
      "Managed Material Runaways.",
      "Instrumentation failure",
    ],
  },
  {
    label: "Life Bottom Bin",
    value: "Life Bottom Bin",
    options: [
      "Level Control",
      "Choking",
      "Auger",
      "Overflows",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Other",
    ],
  },
  {
    label: "Screw Feeder 1-4",
    value: "Screw Feeder 1-4",
    options: [
      "Trip",
      "Choke",
      "Mechanical Failure",
      "Electrical failure",
      "Instrumentation failure",
      "Other",
      "`",
    ],
  },
  {
    label: "Rougher Magsep 1-4",
    value: "Rougher Magsep 1-4",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Life bin level",
      "Operations",
    ],
  },
  {
    label: "Cleaner Magsep 5-8",
    value: "Cleaner Magsep 5-8",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Scavenger Magsep 9-10",
    value: "Scavenger Magsep 9-10",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Magsep Air Filteration System",
    value: "Magsep Air Filteration System",
    options: [
      "Bags",
      "Motor and Gearbox",
      "Choked",
      "Instrument Pulsation",
      "Feeder Discharge",
    ],
  },
  {
    label: "Screw Conveyor to Bucket Elevator 31,32 & 33",
    value: "Screw Conveyor to Bucket Elevator 31,32 & 33",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Bucket Elevator",
    value: "Bucket Elevator",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Scavenger  Feed Screw",
    value: "Scavenger  Feed Screw",
    options: [
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Operations",
      "Other",
    ],
  },
  {
    label: "Total Plant Downtime",
    value: "Total Plant Downtime",
    options: [
      "Plant Modification",
      "Weekly  Plant Maintenance",
      "Instrumentation",
      "Equipment Breakdown Dry section",
      "Equipment Breakdown Separation section",
      "Power Failure MP2",
      "Power Failure Eskom",
      "Power failure Bosveld",
      "Water Supply Bosveld",
      "Water Supply SAOB",
      "Weather conditions",
      "Shut Down Overrun",
      "Strike",
      "No Material due to Rain / Foskor Supply",
      "Other",
    ],
  },
  {
    label: "Instrumentation",
    value: "Instrumentation",
    options: ["Sever Failure", "Power Outage", "Program reboot", "Other"],
  },
  {
    label: "Electrical",
    value: "Electrical",
    options: [
      "MCC Trip",
      "Air cooling system failure",
      "Eskom",
      "Bosveld",
      "MP2",
      "Other",
    ],
  },
  {
    label: "Compressor House",
    value: "Compressor House",
    options: [
      "Compressor failure",
      "Instrumentation failure",
      "Mechanical Failure",
      "Electrical failure",
      "Other",
    ],
  },
  {
    label: "Column2",
    value: "Column2",
    options: [],
  },
  {
    label: "Safety",
    value: "Safety",
    options: ["Structural Damaged", "Incident / accident", "Other"],
  },
];
