import type { NextApiRequest, NextApiResponse } from "next";
import PDFDocument from "pdfkit";
import path from "path";
import { db } from "@/server/db";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions";
import { format } from "date-fns";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  try {
    const session = await getServerSession(req, res, authOptions);
    const user = session?.user;
    const { date, hour } = req.query as { date?: string; hour?: string };
    
    if (!date || !hour) {
      res.status(400).json({ error: "Missing date or hour parameters" });
      return;
    }

    const entries = await db.labInspection.findMany({
      where: { date, hour },
      orderBy: { sample_description: "asc" },
    });

    const doc = new PDFDocument({ size: "A4", margin: 40 });
    
    // Register fonts
    const fontsDir = path.join(process.cwd(), "public/fonts");
    doc.registerFont("OpenAISans-Regular", path.join(fontsDir, "OpenAISans-Regular.8e5ce1c0.otf"));
    doc.registerFont("OpenAISans-Semibold", path.join(fontsDir, "OpenAISans-Semibold.63de4196.otf"));

    // Report Header
    const headerY = doc.page.margins.top;
    doc.font("OpenAISans-Semibold").fontSize(20)
       .text("Hourly Distribution Report", doc.page.margins.left, headerY + 14);
    
    doc.font("OpenAISans-Regular").fontSize(10)
       .text(`Date: ${date}`, doc.page.margins.left, headerY + 54);

    doc.font("OpenAISans-Regular").fontSize(10)
       .text(`Hour: ${hour}`, doc.page.margins.left, headerY + 74);
    
    doc.fontSize(10)
       .text(`Generated on: ${format(new Date(), "PPP p")}`, doc.page.margins.left, headerY + 94);
       // .text(`Generated by: ${user?.name || "Unknown"} (${user?.email || "Unknown"})`, doc.page.margins.left, headerY + 55);

    // Logo
    const logoPath = path.join(process.cwd(), "public/logo.jpg");
    doc.image(logoPath, doc.page.width - doc.page.margins.right - 50, headerY, { 
      width: 50, 
      height: 50 
    });
    
    // **Add horizontal line after logo/header**
    doc.moveDown(1);
    const headerLineY = doc.y;
    doc.strokeColor("#e0e0e0")  // Light grey color
       .lineWidth(0.5)          // Thin line
       .moveTo(doc.page.margins.left, headerLineY)
       .lineTo(doc.page.width - doc.page.margins.right, headerLineY)
       .stroke();
    
    doc.moveDown(1.5);

    // Table Configuration
    const columns = [
      { header: "Sample", key: "sample_description", width: 150 },
      { header: "%Fe", key: "fe_perc", width: 50 },
      { header: "%SiO2", key: "sio_perc", width: 50 },
      { header: "%TiO2", key: "tio_perc", width: 50 },
      { header: "%MgO", key: "mgo_perc", width: 50 },
      { header: "%CaO", key: "cao_perc", width: 50 },
      { header: "%P2O5", key: "p2o5_perc", width: 50 },
      { header: "%Cu", key: "cu_perc", width: 50 },
      { header: "%H2O", key: "moisture", width: 50 },
    ];

    const tableTop = doc.y + 10; // Adjusted spacing
    const tableLeft = doc.page.margins.left;
    const rowHeight = 25;
    const cellPadding = 5;

    // Draw table headers
    doc.font("OpenAISans-Semibold").fontSize(8);
    let xPos = tableLeft;
    let yPos = tableTop;

    // Draw header background
    doc.fillColor("#f5f5f5").rect(tableLeft, tableTop, 
      columns.reduce((sum, col) => sum + col.width, 0), 
      rowHeight).fill();

    // Draw header borders and text
    doc.strokeColor("#cccccc").lineWidth(1);
    columns.forEach((column, i) => {
      const x = xPos;
      doc.strokeOpacity(0.8).rect(x, yPos, column.width, rowHeight).stroke();
      
      doc.fillColor("black").text(
        column.header,
        x + cellPadding,
        yPos + cellPadding,
        { width: column.width - (cellPadding * 2), align: "center" }
      );
      
      xPos += column.width;
    });

    // Reset for data rows
    xPos = tableLeft;
    yPos += rowHeight;

    // Draw data rows with alternating colors
    doc.font("OpenAISans-Regular").fontSize(9);
    
    entries.forEach((row, rowIndex) => {
      // Alternate row colors for better readability
      if (rowIndex % 2 === 0) {
        doc.fillColor("#fafafa").rect(tableLeft, yPos, 
          columns.reduce((sum, col) => sum + col.width, 0), 
          rowHeight).fill();
      }

      // Draw each cell in the row
      columns.forEach((column, colIndex) => {
        const x = tableLeft + columns.slice(0, colIndex).reduce((sum, col) => sum + col.width, 0);
        
        // Draw cell border
        doc.strokeOpacity(0.5).rect(x, yPos, column.width, rowHeight).stroke();
        
        // Draw cell content
        doc.fillColor("black");
        const value = row[column.key as keyof typeof row];
        const textValue = value !== null && value !== undefined ? String(value) : "N/A";
        
        // Center text vertically and horizontally
        const textX = x + cellPadding;
        const textY = yPos + (rowHeight / 2) - 4; // Center vertically
        
        doc.text(textValue, textX, textY, {
          width: column.width - (cellPadding * 2),
          align: "center",
          height: rowHeight - (cellPadding * 2),
          ellipsis: true
        });
      });

      yPos += rowHeight;
      
      // Add page break if we're at the bottom
      if (yPos > doc.page.height - 100) {
        // **Add horizontal line before new page footer**
        const pageFooterLineY = doc.page.height - 80;
        doc.strokeColor("#e0e0e0")
           .lineWidth(0.5)
           .moveTo(doc.page.margins.left, pageFooterLineY)
           .lineTo(doc.page.width - doc.page.margins.right, pageFooterLineY)
           .stroke();
        
        doc.addPage();
        yPos = doc.page.margins.top;
      }
    });

    // Add totals row if needed
    if (entries.length > 0) {
      doc.fillColor("#e8f4fd").rect(tableLeft, yPos, 
        columns.reduce((sum, col) => sum + col.width, 0), 
        rowHeight).fill();
      
      doc.strokeOpacity(0.8).rect(tableLeft, yPos, 
        columns.reduce((sum, col) => sum + col.width, 0), 
        rowHeight).stroke();
      
      doc.font("OpenAISans-Semibold").fontSize(9).fillColor("black");
      doc.text(`Total Samples Tested: ${entries.length}`, tableLeft + cellPadding, yPos + cellPadding);
      yPos += rowHeight;
    }

    // **Add horizontal line before footer (above the footer text)**
    const footerLineY = doc.page.height - doc.page.margins.bottom - 40; // Position above footer
    doc.strokeColor("#e0e0e0")
       .lineWidth(0.5)
       .moveTo(doc.page.margins.left, footerLineY)
       .lineTo(doc.page.width - doc.page.margins.right, footerLineY)
       .stroke();
    
    doc.moveDown(1);

    // Footer
    const footerText = `This is an automatically generated report. © ${new Date().getFullYear()} KBH Group & MP2`;
    const footerY = doc.page.height - doc.page.margins.bottom - 20;
    
    doc.font("OpenAISans-Regular").fontSize(8).fillColor("#666666")
       .text(footerText, tableLeft, footerY, {
         width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
         align: "center"
       });

    // Stream PDF
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="HourlyDistributionReport_${date}_${hour}.pdf"`
    );
    
    doc.pipe(res);
    doc.end();

  } catch (error: any) {
    console.error("exportHourlyDistribution error:", error);
    res.status(500).json({ error: error.message });
  }
}
